channels:
  - conda-forge

dependencies:
  - python=3.10.12                # https://pyreadiness.org/3.10
  - pip=23.2.1                    # https://pip.pypa.io/en/stable/news
  - robocorp-truststore=0.8.0     # https://pypi.org/project/robocorp-truststore/
  - pip:
    - rpaframework==28.6.1        # https://rpaframework.org/releasenotes.html
    - robocorp==2.1.0             # https://pypi.org/project/robocorp
    - robocorp-browser==2.3.3     # https://pypi.org/project/robocorp-browser
    - selenium==4.22.0
    - robocorp==2.1.0
    - pandas==2.2.2